<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\domain\domain.csproj" />
      <ProjectReference Include="..\infra.persistence.sql\infra.persistence.sql.csproj" />
      <ProjectReference Include="..\service.defaults\service.defaults.csproj" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="features.tests" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Carter" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="MediatR" />
      <PackageReference Include="MediatR.Contracts" />
    </ItemGroup>

</Project>
