<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="xunit" />
      <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\features\features.csproj" />
      <ProjectReference Include="..\..\src\infra.persistence.postgre\infra.persistence.postgre.csproj" />
    </ItemGroup>

</Project>
