// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using infra.persistence.postgre;

#nullable disable

namespace infra.persistence.postgre.Migrations
{
    [DbContext(typeof(SparkrockRwcDbContext))]
    partial class SparkrockRwcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("domain.Alerts.StudentAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AbsenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("absence_count");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("alert_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("ResolutionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution_reason");

                    b.Property<string>("ResolutionSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resolution_source");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<int>("SchoolYearStart")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_start");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int>("ThresholdAtRaise")
                        .HasColumnType("integer")
                        .HasColumnName("threshold_at_raise");

                    b.HasKey("Id")
                        .HasName("pk_student_alerts");

                    b.HasIndex("SchoolId", "SchoolYearStart")
                        .HasDatabaseName("ix_student_alerts_school_id_school_year_start");

                    b.HasIndex("StudentId", "SchoolYearStart")
                        .HasDatabaseName("ix_student_alerts_student_id_school_year_start");

                    b.HasIndex("StudentId", "AlertType", "SchoolYearStart", "SchoolId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_alerts_open_episode")
                        .HasFilter("resolved_at IS NULL AND is_deleted = false");

                    b.ToTable("student_alerts", null, t =>
                        {
                            t.HasCheckConstraint("ck_student_alerts_absence_count_not_negative", "absence_count >= 0");

                            t.HasCheckConstraint("ck_student_alerts_resolution_consistent", "(resolved_at IS NULL AND resolution_source IS NULL) OR (resolved_at IS NOT NULL AND resolution_source IS NOT NULL)");

                            t.HasCheckConstraint("ck_student_alerts_school_year_start", "school_year_start BETWEEN 1900 AND 2100");
                        });
                });

            modelBuilder.Entity("domain.Attendance.AttendanceSubmissionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AttendDate")
                        .HasColumnType("date")
                        .HasColumnName("attend_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.HasKey("Id")
                        .HasName("pk_attendance_submission_logs");

                    b.HasIndex("SchoolId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_submission_logs_school_id_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("SchoolId", "SubmittedAt", "Id")
                        .HasDatabaseName("ix_submission_logs_school_id_submitted_at_id");

                    b.ToTable("attendance_submission_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_submission_logs_record_count_not_negative", "record_count >= 0");
                        });
                });

            modelBuilder.Entity("domain.Attendance.StudentAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttendCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("attend_code");

                    b.Property<string>("AttendCodeDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("attend_code_description");

                    b.Property<DateOnly>("AttendDate")
                        .HasColumnType("date")
                        .HasColumnName("attend_date");

                    b.Property<Guid>("AttendanceCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_code_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_absent");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsExcused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_excused");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<int?>("MinutesLate")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_late");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.HasKey("Id")
                        .HasName("pk_student_attendances");

                    b.HasIndex("AttendanceCodeId")
                        .HasDatabaseName("ix_student_attendances_attendance_code_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_attendances_legacy_id")
                        .HasFilter("legacy_id IS NOT NULL");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_attendances_student_id");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_student_attendances_submission_id");

                    b.HasIndex("TermId")
                        .HasDatabaseName("ix_student_attendances_term_id");

                    b.HasIndex("SchoolId", "AttendDate")
                        .HasDatabaseName("ix_student_attendances_school_id_attend_date");

                    b.HasIndex("StudentId", "AttendDate")
                        .IsUnique()
                        .HasDatabaseName("ix_student_attendances_student_id_attend_date")
                        .HasFilter("is_deleted = false");

                    b.ToTable("student_attendances", null, t =>
                        {
                            t.HasCheckConstraint("ck_student_attendances_minutes_late_not_negative", "minutes_late IS NULL OR minutes_late >= 0");
                        });
                });

            modelBuilder.Entity("domain.Attendance.StudentAttendanceSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<int>("SchoolYearStart")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_start");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int>("TotalAbsences")
                        .HasColumnType("integer")
                        .HasColumnName("total_absences");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_student_attendance_summaries");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_student_attendance_summaries_school_id");

                    b.HasIndex("StudentId", "SchoolYearStart")
                        .IsUnique()
                        .HasDatabaseName("ix_summaries_student_id_school_year_start");

                    b.ToTable("student_attendance_summaries", null, t =>
                        {
                            t.HasCheckConstraint("ck_student_attendance_summaries_school_year_start", "school_year_start BETWEEN 1900 AND 2100");

                            t.HasCheckConstraint("ck_student_attendance_summaries_total_absences_not_negative", "total_absences >= 0");
                        });
                });

            modelBuilder.Entity("domain.AttendanceCodes.AttendanceCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_absent");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsExcused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_excused");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_attendance_codes");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_codes_legacy_id")
                        .HasFilter("legacy_id IS NOT NULL");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_codes_value");

                    b.ToTable("attendance_codes", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_codes_value_upper", "value = upper(value)");
                        });
                });

            modelBuilder.Entity("domain.Import.LegacyImportAnomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnomalyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("anomaly_code");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detail");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.HasKey("Id")
                        .HasName("pk_legacy_import_anomalies");

                    b.HasIndex("BatchId", "AnomalyCode")
                        .HasDatabaseName("ix_import_anomalies_batch_id_anomaly_code");

                    b.ToTable("legacy_import_anomalies", (string)null);
                });

            modelBuilder.Entity("domain.SchoolTerms.SchoolTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_school_terms");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_school_terms_legacy_id")
                        .HasFilter("legacy_id IS NOT NULL");

                    b.HasIndex("SchoolId", "StartDate", "EndDate")
                        .HasDatabaseName("ix_school_terms_school_id_start_date_end_date");

                    b.ToTable("school_terms", null, t =>
                        {
                            t.HasCheckConstraint("ck_school_terms_end_date_not_before_start_date", "end_date >= start_date");
                        });
                });

            modelBuilder.Entity("domain.Schools.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AbsenceAlertThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("absence_alert_threshold");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_schools");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_schools_legacy_id")
                        .HasFilter("legacy_id IS NOT NULL");

                    b.ToTable("schools", null, t =>
                        {
                            t.HasCheckConstraint("ck_schools_absence_alert_threshold_positive", "absence_alert_threshold IS NULL OR absence_alert_threshold >= 1");
                        });
                });

            modelBuilder.Entity("domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Grade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grade");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_students_legacy_id")
                        .HasFilter("legacy_id IS NOT NULL");

                    b.HasIndex("SchoolId", "IsActive")
                        .HasDatabaseName("ix_students_school_id_is_active");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("domain.TestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("TestProperty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("test_property");

                    b.HasKey("Id")
                        .HasName("pk_test_entities");

                    b.ToTable("test_entities", (string)null);
                });

            modelBuilder.Entity("domain.Alerts.StudentAlert", b =>
                {
                    b.HasOne("domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_alerts_schools_school_id");

                    b.HasOne("domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_alerts_students_student_id");
                });

            modelBuilder.Entity("domain.Attendance.AttendanceSubmissionLog", b =>
                {
                    b.HasOne("domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_logs_schools_school_id");
                });

            modelBuilder.Entity("domain.Attendance.StudentAttendance", b =>
                {
                    b.HasOne("domain.AttendanceCodes.AttendanceCode", null)
                        .WithMany()
                        .HasForeignKey("AttendanceCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_attendances_attendance_codes_attendance_code_id");

                    b.HasOne("domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_attendances_schools_school_id");

                    b.HasOne("domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_attendances_students_student_id");

                    b.HasOne("domain.Attendance.AttendanceSubmissionLog", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_attendances_submission_logs_submission_id");

                    b.HasOne("domain.SchoolTerms.SchoolTerm", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_attendances_school_terms_term_id");
                });

            modelBuilder.Entity("domain.Attendance.StudentAttendanceSummary", b =>
                {
                    b.HasOne("domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_summaries_schools_school_id");

                    b.HasOne("domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_summaries_students_student_id");
                });

            modelBuilder.Entity("domain.SchoolTerms.SchoolTerm", b =>
                {
                    b.HasOne("domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_school_terms_schools_school_id");
                });

            modelBuilder.Entity("domain.Students.Student", b =>
                {
                    b.HasOne("domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_schools_school_id");
                });
#pragma warning restore 612, 618
        }
    }
}
