<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UserSecretsId>b9c41a98-f987-4292-b35b-75416f5a75a6</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.AppHost" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\api\api.csproj" />
    </ItemGroup>

</Project>
