<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\features\features.csproj" />
      <ProjectReference Include="..\infra.persistence.postgre\infra.persistence.postgre.csproj" />
      <ProjectReference Include="..\service.defaults\service.defaults.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Scalar.AspNetCore" Version="2.16.11" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    </ItemGroup>

</Project>
